```
                num   nominalCat  ordinalCat
                |age|city|gender|review|
    age = simple imputer
    city/gender = One Hot Encoding 
    review = Ordinal Encoding (as it is a input column)

PROBLEM YE HAI KI 3 ALAG ALAG METHODS LAGANE PADENGE USKE BAAD 3 NUMPY ARRAYS BANEGI UNKO HAME FIRSE MERGE KARNA HOGA in a big NUMPY Array ISKE LIYE HUM COLUMN TRANFORMER USE KARTE HAI
```

## NORMAL METHOD OF FEATURE TRANSFORMATION

In [4]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [10]:
df = pd.read_csv('covid_toy.csv')
df

age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [6]:
print(df['cough'].value_counts())
print(df['city'].value_counts())

Mild      62
Strong    38
Name: cough, dtype: int64
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64


In [7]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [9]:
X_train

age  gender  fever   cough       city
82   24    Male   98.0    Mild    Kolkata
88    5  Female  100.0    Mild    Kolkata
51   11  Female  100.0  Strong    Kolkata
49   44    Male  104.0    Mild     Mumbai
34   74    Male  102.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
45   72    Male   99.0    Mild  Bangalore
75    5    Male  102.0    Mild    Kolkata
76   80    Male  100.0    Mild  Bangalore
10   75  Female    NaN    Mild      Delhi
78   11    Male  100.0    Mild  Bangalore

[80 rows x 5 columns]

## Aam Zindagi

fever = simple imputer
city/gender = one hot encoding
cough = ordinal encoding
has_covid = label encoder

### Preparing Fever Using Simple Imputer

In [12]:
# adding simple imputer to fever col
si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[['fever']])

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever.shape

(80, 1)

In [13]:
X_train_fever

array([[ 98.        ],
       [100.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [100.91666667],
       [100.91666667],
       [ 99.        ],
       [101.        ],
       [104.        ],
       [ 99.        ],
       [104.        ],
       [ 98.        ],
       [103.        ],
       [101.        ],
       [ 99.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [101.        ],
       [ 98.        ],
       [100.        ],
       [100.91666667],
       [103.        ],
       [104.        ],
       [ 98.        ],
       [100.91666667],
       [ 99.        ],
       [101.        ],
       [100.91666667],
       [ 98.        ],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [ 98.        ],
       [100.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [103.        ],
       [101.        ],
       [101.        ],
       [103.        ],
       [101

### Prepare cough column

In [20]:
# Ordinalencoding -> cough     [mil, strong] -> [0,1] =[ascending order]
oe = OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [21]:
# OneHotEncoding -> gender = 2 category ,city = 4 category so removing first column to minumize mulicollinearity gender = 1, city = 3
ohe = OneHotEncoder(drop='first',sparse=False)
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

C:\Users\bltat\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
C:\Users\bltat\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 4)

In [22]:
X_train_gender_city

array([[1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],


In [23]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [24]:
X_train_age

array([[24],
       [ 5],
       [11],
       [44],
       [74],
       [71],
       [23],
       [59],
       [47],
       [18],
       [25],
       [56],
       [23],
       [70],
       [68],
       [14],
       [42],
       [16],
       [83],
       [64],
       [71],
       [47],
       [79],
       [60],
       [54],
       [69],
       [82],
       [66],
       [19],
       [20],
       [65],
       [60],
       [55],
       [51],
       [81],
       [27],
       [75],
       [83],
       [73],
       [73],
       [19],
       [ 8],
       [50],
       [15],
       [42],
       [22],
       [12],
       [34],
       [69],
       [64],
       [65],
       [19],
       [64],
       [34],
       [27],
       [16],
       [49],
       [12],
       [65],
       [ 6],
       [48],
       [10],
       [49],
       [82],
       [46],
       [83],
       [13],
       [49],
       [26],
       [ 5],
       [42],
       [38],
       [17],
       [82],
       [24],
       [72],
       [ 5],

In [25]:
### concatenating using np.concatenate(all the columns, axis = row)

In [26]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

In [27]:
X_train_transformed

array([[ 24.        ,  98.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 11.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 44.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 74.        , 102.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 71.        , 100.91666667,   1.        ,   0.        ,
          1.        ,   0.        ,   1.        ],
       [ 23.        , 100.91666667,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 59.        ,  99.        ,   0.        ,   1.        ,
          0.        ,   0.        ,   1.        ],
       [ 47.        , 101.        ,   1.        ,   0.        ,
          0.    

## Mentos Zindagi

In [28]:
from sklearn.compose import ColumnTransformer

In [ ]:
# transformer = ColumnTransformer(transformers=[
#                                             (name if the transformer, transformer, columns to apply to)],
#                           remainder='passthrough') # passthrough the columns that are not transformed

In [29]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [30]:
transformer.fit_transform(X_train).shape

C:\Users\bltat\AppData\Roaming\Python\Python310\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


(80, 7)

In [31]:
transformer.transform(X_test).shape

(20, 7)